name: anymex
description: "An Anilist Client"
publish_to: "GitHub"
version: 3.0.2+24

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # âœ… Replaced incompatible expressive_loading_indicator
  loading_animation_widget: ^1.2.1

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.0
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.4
  package_info_plus: ^5.0.1

  path: ^1.9.0
  path_provider: any
  permission_handler: ^11.3.1
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  super_sliver_list: ^0.4.1
  share_plus: ^11.0.0
  url_launcher: any
  volume_controller: ^3.4.0 
  screen_brightness: ^2.1.7 
  window_manager: ^0.4.3
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  app_links: ^6.4.0
  preload_page_view: ^0.2.0

  archive: any
  image: any
  flutter_widget_from_html: ^0.17.0
  timeago: ^3.7.1
  flutter_staggered_animations: ^1.1.1
  material_symbols_icons: ^4.2867.0
  fuzzywuzzy: ^1.2.0
  expressive_loading_indicator: ^0.0.1
  photo_view: ^0.15.0
dev_dependencies:
  build_runner: ^2.4.11
  change_app_package_name: ^1.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  inno_bundle: ^0.7.4

# dependency_overrides:
#   path: ^1.9.1

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256
  macos:
    generate: false
    image_path: "assets/images/logo.png"

flutter_native_splash:
  fullscreen: true
  color: "#000000"
  image: assets/images/logo.png
  android_12:
    color: "#000000"
    image: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf

inno_bundle:
  id: 8fbd47cb-d6e1-5343-a9f6-61661647c94c
  publisher: Ryan Yuuki
  name: AnymeX
  version: 3.0.2
  admin: auto
  installer_icon: ./anymex.ico
